<a href="https://colab.research.google.com/github/shaily-uni/data-science-python/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arravali=np.array(np.random.randint(10,45,(8,2)))
print(arravali)
print(arravali.shape)

[[40 34]
 [25 33]
 [21 33]
 [10 26]
 [13 16]
 [28 24]
 [26 10]
 [44 34]]
(8, 2)


In [6]:
import numpy as np
arravali=np.array(np.random.randint(10,45,(8,2)))
nilgiri=np.transpose(arravali)
print(nilgiri)
print(nilgiri.shape)

[[28 17 22 18 44 31 39 36]
 [42 25 22 39 25 26 13 21]]
(2, 8)


In [7]:
randomarray=np.array(np.random.randint(10,45,(3,2,4)))
print(randomarray)
print(randomarray.shape)

[[[34 40 14 41]
  [26 13 16 11]]

 [[33 26 23 35]
  [24 28 34 21]]

 [[15 38 30 42]
  [17 14 12 14]]]
(3, 2, 4)


In [8]:
transposearray=np.transpose(randomarray)
print(transposearray)
print(transposearray.shape)

[[[34 33 15]
  [26 24 17]]

 [[40 26 38]
  [13 28 14]]

 [[14 23 30]
  [16 34 12]]

 [[41 35 42]
  [11 21 14]]]
(4, 2, 3)


In [9]:
random_cohort=np.array(np.random.randint(10,45,(3,8)))
print(random_cohort)
print(random_cohort.shape)


[[31 17 21 25 33 11 40 38]
 [20 14 23 26 42 36 42 10]
 [24 27 11 26 12 12 39 10]]
(3, 8)


In [11]:
new_shape=(2,6,2)
reshaped_random_cohort=np.reshape(random_cohort,new_shape)
print(reshaped_random_cohort)
(random_cohort,new_shape)
print(reshaped_random_cohort.shape)

[[[31 17]
  [21 25]
  [33 11]
  [40 38]
  [20 14]
  [23 26]]

 [[42 36]
  [42 10]
  [24 27]
  [11 26]
  [12 12]
  [39 10]]]
(2, 6, 2)


In [12]:
random_3d_cohort=np.array(np.random.randint(10,45,(2,4,6)))
print(random_3d_cohort)
print(random_3d_cohort.shape)


[[[18 36 34 36 32 41]
  [40 31 40 42 42 31]
  [23 31 21 36 38 12]
  [12 13 43 21 32 11]]

 [[15 10 36 39 29 39]
  [35 43 15 38 26 23]
  [39 20 17 19 29 10]
  [23 18 13 17 26 37]]]
(2, 4, 6)


In [13]:
random_3d_cohort.flatten()

array([18, 36, 34, 36, 32, 41, 40, 31, 40, 42, 42, 31, 23, 31, 21, 36, 38,
       12, 12, 13, 43, 21, 32, 11, 15, 10, 36, 39, 29, 39, 35, 43, 15, 38,
       26, 23, 39, 20, 17, 19, 29, 10, 23, 18, 13, 17, 26, 37])

In [16]:
import numpy as np
a=np.random.randint(10,20,(2,3,4))
print(a)
print(a.shape)
np.insert(a,1,100,axis=0)
np.insert(a,0,50,axis=1)
np.insert(a,0,200,axis=2)

[[[19 15 18 16]
  [14 15 18 16]
  [11 13 11 10]]

 [[10 15 14 17]
  [19 14 15 10]
  [16 11 10 14]]]
(2, 3, 4)


array([[[200,  19,  15,  18,  16],
        [200,  14,  15,  18,  16],
        [200,  11,  13,  11,  10]],

       [[200,  10,  15,  14,  17],
        [200,  19,  14,  15,  10],
        [200,  16,  11,  10,  14]]])

In [17]:
a=np.random.randint(2,6,(2,3,3))
print(a)
print(a.shape)

[[[2 3 5]
  [3 3 4]
  [2 5 5]]

 [[5 5 3]
  [5 3 2]
  [2 2 2]]]
(2, 3, 3)


In [18]:
np.append(a,50)

array([ 2,  3,  5,  3,  3,  4,  2,  5,  5,  5,  5,  3,  5,  3,  2,  2,  2,
        2, 50])

In [21]:
b=np.random.randint(2,6,(2,1,3))
print(b)


[[[3 3 5]]

 [[4 3 2]]]


In [22]:
print(a)
print(a.shape)

[[[2 3 5]
  [3 3 4]
  [2 5 5]]

 [[5 5 3]
  [5 3 2]
  [2 2 2]]]
(2, 3, 3)


In [23]:
np.append(a,b,axis=1)

array([[[2, 3, 5],
        [3, 3, 4],
        [2, 5, 5],
        [3, 3, 5]],

       [[5, 5, 3],
        [5, 3, 2],
        [2, 2, 2],
        [4, 3, 2]]])

In [24]:
a=np.random.randint(2,6,(2,3,3))
print(a)
print(a.shape)

[[[5 3 3]
  [4 2 2]
  [4 4 3]]

 [[3 5 4]
  [2 5 3]
  [4 2 5]]]
(2, 3, 3)


In [25]:
np.delete(a,(0),axis=0)

array([[[3, 5, 4],
        [2, 5, 3],
        [4, 2, 5]]])

In [26]:
np.delete(a,(0,2),axis=1)

array([[[4, 2, 2]],

       [[2, 5, 3]]])

In [27]:
a

array([[[5, 3, 3],
        [4, 2, 2],
        [4, 4, 3]],

       [[3, 5, 4],
        [2, 5, 3],
        [4, 2, 5]]])

In [29]:
np.delete(a,(0,1),axis=2)

array([[[3],
        [2],
        [3]],

       [[4],
        [3],
        [5]]])

In [32]:
a=np.random.randint(0,2,(2,3,3))
print(a)
print(a.shape)


[[[0 1 0]
  [0 1 1]
  [1 0 1]]

 [[1 1 0]
  [1 1 0]
  [1 1 1]]]
(2, 3, 3)


In [33]:
np.unique(a)

array([0, 1])

In [34]:
np.unique(a,return_counts=True)

(array([0, 1]), array([ 6, 12]))

In [35]:
np.unique(a,return_counts=True,return_index=True)

(array([0, 1]), array([0, 1]), array([ 6, 12]))

In [36]:
a=[1,2,3]
b=a
b[0]=10
print(b)
print(a)


[10, 2, 3]
[10, 2, 3]


In [37]:
a=[1,2,3]
b=a.copy()
b[0]=10
print(b)
print(a)

[10, 2, 3]
[1, 2, 3]


In [38]:
a=np.array([1,2,3])
b=a.copy()
b[0]=-999
print(b)
print(a)

[-999    2    3]
[1 2 3]


In [40]:
a=np.random.randint(2,6,(2,4))
print(a)
b=np.random.randint(0,5,(2,4))
np.multiply(a,b)

[[5 3 2 5]
 [5 2 3 3]]


array([[10, 12,  0, 15],
       [ 5,  2,  6,  0]])